package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var wikiIndexCmd = &cobra.Command{
	Use:   "index",
	Short: "Rebuild data/wiki/index.md",
	RunE: func(cmd *cobra.Command, args []string) error {
		return rebuildIndex()
	},
}

func rebuildIndex() error {
	wikiDir := "data/wiki"
	indexPath := filepath.Join(wikiDir, "index.md")

	// Collect all pages by type
	type entry struct {
		title  string
		slug   string
		source string
	}
	pages := map[string][]entry{
		"entities": {},
		"concepts": {},
		"sources":  {},
	}

	for _, t := range []string{"entities", "concepts", "sources"} {
		dir := filepath.Join(wikiDir, t)
		if err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".md") {
				return nil
			}
			name := strings.TrimSuffix(info.Name(), ".md")
			source := path

			if t == "entities" {
				// entities/Subdirectory/Title.md
				rel, _ := filepath.Rel(dir, path)
				parts := strings.Split(filepath.ToSlash(rel), "/")
				if len(parts) == 2 {
					name = strings.TrimSuffix(parts[1], ".md")
				}
			} else if t == "sources" {
				// sources/Title_date.md → strip date suffix
				parts := strings.Split(name, "_")
				if len(parts) > 1 && len(parts[len(parts)-1]) == 10 {
					name = strings.Join(parts[:len(parts)-1], "_")
				}
			}

			pages[t] = append(pages[t], entry{title: name, slug: name, source: source})
			return nil
		}); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("walk %s: %w", t, err)
		}
	}

	// Build index content
	var b strings.Builder
	b.WriteString("# 知识库索引\n\n")
	b.WriteString(fmt.Sprintf("> Generated by llm-wiki at %s\n\n", "now"))

	for _, t := range []string{"entities", "concepts", "sources"} {
		entries := pages[t]
		b.WriteString(fmt.Sprintf("## %s (%d)\n", strings.ToUpper(t[:1])+t[1:], len(entries)))
		if len(entries) == 0 {
			b.WriteString("*（空）*\n\n")
			continue
		}
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("- [[%s]]\n", e.title))
		}
		b.WriteString("\n")
	}

	// Add backlinks section
	b.WriteString("## 最近更新\n")
	b.WriteString("*(见 log.md)*\n")

	if err := os.WriteFile(indexPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write index: %w", err)
	}

	fmt.Printf("✓ index.md rebuilt — entities=%d concepts=%d sources=%d\n",
		len(pages["entities"]), len(pages["concepts"]), len(pages["sources"]))
	return nil
}
