feeds:
    - name: hn-ai
      url: https://hnrss.org/frontpage
      tags:
        - AI
        - LLM
    - name: rust-blog
      url: https://blog.rust-lang.org/feed.xml
      tags:
        - Rust
    - name: example_com
      url: https://example.com/rss
      tags: []
interval: '*/10 * * * *'
